# Generated by Django 4.0.3 on 2022-04-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='ratingAuthor',
        ),
    ]
